In [4]:
from sklearn.metrics import classification_report
y_true = [1, 1, 2, 2, 2]
y_pred = [1, 1, 2, 2, 1]
target_names = ['class 1', 'class 2']
print(classification_report(y_true, y_pred, target_names=target_names))

             precision    recall  f1-score   support

    class 1       0.67      1.00      0.80         2
    class 2       1.00      0.67      0.80         3

avg / total       0.87      0.80      0.80         5



In [7]:
from sklearn.metrics import classification_report
y_true = [0, 0, 1, 1, 1]
y_pred = [0, 0, 1, 1, 0]
target_names = ['class 0', 'class 1']
print(classification_report(y_true, y_pred))

             precision    recall  f1-score   support

          0       0.67      1.00      0.80         2
          1       1.00      0.67      0.80         3

avg / total       0.87      0.80      0.80         5



In [11]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average=None)

(array([0.66666667, 0.        , 0.        ]),
 array([1., 0., 0.]),
 array([0.8, 0. , 0. ]),
 array([2, 2, 2]))

In [22]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average='weighted')

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [23]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average='macro')

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [24]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average='micro')

(0.3333333333333333, 0.3333333333333333, 0.3333333333333333, None)