In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# read in the iris data
iris = load_iris()

# create X (features) and y (response)
X = iris.data
Y = iris.target
print(type(X))
print(f"X = {X}")

<class 'numpy.ndarray'>
X = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6

In [5]:
print(f'{len(X[0])}')

4


In [6]:
len_x = len(X)
len_y = len(Y)

print(f'len_x = {len_x}')
print(f'len_y = {len_y}')

len_x = 150
len_y = 150


In [3]:
# use train/test split with different random_state values# use t 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=4)
len_x_train = len(X_train)
len_x_test = len(X_test)
len_y_train = len(Y_train)
len_y_test = len(Y_test)

print(f'len_x_train = {len_x_train}')
print(f'len_x_test = {len_x_test}')
print(f'len_y_train = {len_y_train}')
print(f'len_y_trst = {len_y_test}')

print(X_train)

len_x_train = 112
len_x_test = 38
len_y_train = 112
len_y_trst = 38
[[6.7 3.1 4.7 1.5]
 [5.1 3.8 1.6 0.2]
 [7.7 3.  6.1 2.3]
 [5.  3.4 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.4 3.7 1.5 0.2]
 [6.4 2.8 5.6 2.2]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [5.9 3.  4.2 1.5]
 [6.1 3.  4.6 1.4]
 [6.5 3.  5.5 1.8]
 [5.2 3.5 1.5 0.2]
 [5.6 2.5 3.9 1.1]
 [7.7 2.6 6.9 2.3]
 [6.3 3.4 5.6 2.4]
 [6.2 2.9 4.3 1.3]
 [5.7 2.9 4.2 1.3]
 [5.  3.5 1.6 0.6]
 [5.6 2.9 3.6 1.3]
 [6.  2.2 5.  1.5]
 [5.5 2.6 4.4 1.2]
 [4.6 3.4 1.4 0.3]
 [5.6 3.  4.1 1.3]
 [5.1 3.4 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [6.8 3.  5.5 2.1]
 [6.7 3.  5.  1.7]
 [6.5 3.2 5.1 2. ]
 [6.  3.4 4.5 1.6]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [6.9 3.2 5.7 2.3]
 [5.4 3.4 1.5 0.4]
 [5.5 2.4 3.8 1.1]
 [6.3 3.3 6.  2.5]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.9 1.8]
 [6.5 2.8 4.6 1.5]
 [5.9 3.  5.1 1.8]
 [6.3 2.5 4.9 1.5]
 [4.9 3.1 1.5 0.1]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [7.1 3.  5.9 2.1]
 [5.5 3.5 1.3 0.2]
 [6.4 2.7 5.3 1.9]
 [5.5 2.3 4.  1.3]
 [6.9 3.1 5.4 2.1]
 

In [4]:
print(Y_train)
one_count = list(Y_train).count(1)
two_count = list(Y_train).count(2)
zero_count = list(Y_train).count(0)
print(f'1 num = {one_count}')
print(f'2 num = {two_count}')
print(f'0 num = {zero_count}')


'''
Y_train[Y_train==2] = 0
print(Y_train)
one_count = list(Y_train).count(1)
two_count = list(Y_train).count(2)
zero_count = list(Y_train).count(0)
print(f'1 num = {one_count}')
print(f'2 num = {two_count}')
print(f'0 num = {zero_count}')
'''


[1 0 2 0 1 0 2 0 0 1 1 2 0 1 2 2 1 1 0 1 2 1 0 1 0 1 2 1 2 1 0 2 2 0 1 2 0
 2 1 2 1 0 2 1 2 0 2 1 2 1 2 1 1 2 1 1 2 1 1 0 2 0 1 0 1 1 1 1 0 2 2 1 1 1
 0 0 2 2 0 0 0 2 0 0 2 2 1 0 0 0 2 1 0 0 2 1 2 0 0 2 1 1 1 2 2 1 2 1 1 2 2
 2]
1 num = 42
2 num = 38
0 num = 32


"\nY_train[Y_train==2] = 0\nprint(Y_train)\none_count = list(Y_train).count(1)\ntwo_count = list(Y_train).count(2)\nzero_count = list(Y_train).count(0)\nprint(f'1 num = {one_count}')\nprint(f'2 num = {two_count}')\nprint(f'0 num = {zero_count}')\n"

In [5]:
# check classification accuracy of KNN with K=5
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)
Y_pred = knn.predict(X_test)
print(metrics.accuracy_score(Y_test, Y_pred))

0.9736842105263158


In [6]:
# simulate splitting a dataset of 25 observations into 5 folds
#from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
skf = StratifiedKFold(n_splits=5, random_state=25, shuffle=False)
#skf = KFold(n_splits=5, random_state=25, shuffle=False)

# print the contents of each training and testing set
print('{} {:^61} {}'.format('Iteration', 'Training set observations', 'Testing set observations'))

iteration = 0
for train_index, test_index in skf.split(X_train, Y_train):
    print('{} {} {}'.format(iteration, train_index, test_index))
    list_test = [Y_train[x] for x in test_index]
    one_count = list_test.count(1)
    two_count = list_test.count(2)
    zero_count = list_test.count(0)
    print(f'list_test = {list_test}')
    print(f'1 num = {one_count}')
    print(f'2 num = {two_count}')
    print(f'0 num = {zero_count}')
    iteration += 1
    
#for iteration, data in enumerate(kf, start=1):
#    print('{:^9} {} {:^25}'.format(iteration, data[0], data[1]))

Iteration                   Training set observations                   Testing set observations
0 [ 22  23  24  25  27  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 26 28]
list_test = [1, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 2]
1 num = 9
2 num = 8
0 num = 7
1 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  26  28  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report

In [8]:
# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

In [14]:
#scores = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
scores = ['precision_macro', 'recall_macro', 'accuracy', 'f1_macro']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    skf = StratifiedKFold(n_splits=10, random_state=25, shuffle=True)
    clf = GridSearchCV(SVC(), tuned_parameters, cv=skf, scoring = score)
    clf.fit(X_train, Y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    Y_true, Y_pred = Y_test, clf.predict(X_test)
    print(classification_report(Y_true, Y_pred))
    print()

# Tuning hyper-parameters for precision_macro



/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/an

Best parameters set found on development set:

{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}

Grid scores on development set:

0.125 (+/-0.010) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.125 (+/-0.010) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.942 (+/-0.039) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.125 (+/-0.010) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.986 (+/-0.055) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.942 (+/-0.039) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.986 (+/-0.059) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.986 (+/-0.055) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.986 (+/-0.059) for {'C': 1, 'kernel': 'linear'}
0.972 (+/-0.070) for {'C': 10, 'kernel': 'linear'}
0.982 (+/-0.077) for {'C': 100, 'kernel': 'linear'}
0.982 (+/-0.077) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.

           

/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/coslate/anaconda3/

Best parameters set found on development set:

{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}

Grid scores on development set:

0.182 (+/-0.010) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.182 (+/-0.010) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.922 (+/-0.054) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.182 (+/-0.010) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.983 (+/-0.065) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.922 (+/-0.054) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.983 (+/-0.070) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.983 (+/-0.065) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.983 (+/-0.070) for {'C': 1, 'kernel': 'linear'}
0.966 (+/-0.083) for {'C': 10, 'kernel': 'linear'}
0.974 (+/-0.114) for {'C': 100, 'kernel': 'linear'}
0.974 (+/-0.114) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.

           

In [29]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)  
StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
for train_index, test_index in skf.split(X, y):
    print("train_index = ", train_index, "\ntest_index = ", test_index)
    print(f'type(train_index) = {type(train_index)}')
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    print(f"TRAIN_X_VAL = {X_train}")
    print(f"TRAIN_Y_VAL = {y_train}")
    print(f"TEST_X_VAL = {X_test}")
    print(f"TEST_Y_VAL = {y_test}")
    print('------')

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
train_index =  [1 3] 
test_index =  [0 2]
type(train_index) = <class 'numpy.ndarray'>
TRAIN_X_VAL = [[3 4]
 [3 4]]
TRAIN_Y_VAL = [0 1]
TEST_X_VAL = [[1 2]
 [1 2]]
TEST_Y_VAL = [0 1]
------
train_index =  [0 2] 
test_index =  [1 3]
type(train_index) = <class 'numpy.ndarray'>
TRAIN_X_VAL = [[1 2]
 [1 2]]
TRAIN_Y_VAL = [0 1]
TEST_X_VAL = [[3 4]
 [3 4]]
TEST_Y_VAL = [0 1]
------


In [30]:
index = np.array([1, 3])
print(type(index))
#X[index]

<class 'numpy.ndarray'>
