In [1]:
import numpy as np
import pandas as pd
import time

# @param dfFile: pandas.DataFrame ('nba_preprocessed.csv')
# @param dateStart, dateEnd: str in the format of 'YYYY-MM-DD'
# @param attriToDrop: list[str]
# @return X, Y: pandas.DataFrame
# featureExtraction() outputs X, Y for model training.
# Game date can be assigned
# Attribute to be dropped can be assigned
def featureExtraction(dfFile, dateStart='1000-01-01', dateEnd='2999-12-31', attriToDrop=None):
    df = pd.read_csv(dfFile)
    
    # Date selection
    df = df.loc[lambda df: (df.Date_A > dateStart) & (df.Date_A < dateEnd), :].reset_index(drop=True)
    
    # Get label Y
    Y = df[['W/L_A']]
    Y = Y.rename(columns={'W/L_A': 'Label'})
    
    # Get attributes X
    colToDrop = ['Team_A', 'Date_A', 'W/L_A', 'Score_A', 'Opponent_A', 'Team_B', 'Date_B', 'W/L_B', 'Home/Away_B', 'Score_B', 'Opponent_B']
    colToDrop += attriToDrop if attriToDrop else []
    X = df.drop(columns = colToDrop)
    
    return X, Y

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.svm import SVC
import numpy as np
import operator
%matplotlib inline

def CrossValidationGridSearchNested(X_data, Y_data, num_trials, fold_num, est_classifcation, tuned_param, scoring):
    max_score = -1
    best_estimator = est_classifcation
    
    for i in range(num_trials):
        inner_cv = StratifiedKFold(n_splits=fold_num, random_state=i, shuffle=True)
        outer_cv = StratifiedKFold(n_splits=fold_num, random_state=i+1, shuffle=True)

        # Non_nested parameter search and scoring
        clf = GridSearchCV(estimator=est_classifcation, param_grid=tuned_param, cv=inner_cv, scoring=scoring)
        clf.fit(X_data, Y_data)
        
        # CV with parameter optimization
        param_score = cross_val_score(clf.best_estimator_, X=X_data, y=Y_data, cv=outer_cv, scoring=scoring).mean()
        if(param_score > max_score):
            max_score = param_score
            best_estimator = clf.best_estimator_
            
        progress = (i+1)/num_trials*100
        print(f'> progress = {progress}%')
    
    return (max_score, best_estimator)

# Execution

## -Feature Extraction

In [3]:
dfFile = '../NBA_Ino_part/nba_preprocessed.csv'
dateStart = '2017-10-01'
dateEnd = '2018-04-30'
# X, Y = featureExtraction(dfFile, dateStart, dateEnd)
X, Y = featureExtraction(dfFile, attriToDrop=['PTS_A', 'PTS_B'], dateStart=dateStart, dateEnd=dateEnd)
# X, Y = featureExtraction(dfFile)

In [4]:
X

Home/Away_A  FG%_A  FGM_A  FGA_A  3P%_A  3PM_A  3PA_A  FT%_A  FTM_A  \
0               0  0.468     36     77  0.481     13     27  0.917     11   
1               1  0.435     37     85  0.333     10     30  0.600     12   
2               1  0.488     39     80  0.348      8     23  0.783     18   
3               0  0.384     38     99  0.258      8     31  0.600      9   
4               0  0.462     42     91  0.200      4     20  0.739     17   
5               0  0.505     47     93  0.550     11     20  0.864     19   
6               0  0.412     35     85  0.439     18     41  0.710     22   
7               1  0.534     47     88  0.500     16     32  0.655     19   
8               1  0.450     36     80  0.391      9     23  0.560     14   
9               1  0.460     40     87  0.250      6     24  0.815     22   
10              1  0.478     44     92  0.273      9     33  0.750     15   
11              1  0.463     38     82  0.333      9     27  0.773     17   
12              1  0.529     46     87  0.414     12     29  0.778     21   
13              0  0.357     30     84  0.281      9     32  0.867     13   
14              1  0.629     56     89  0.514     18     35  0.762     16   
15              0  0.429     36     84  0.419     13     31  0.686     24   
16              0  0.488     42     86  0.469     15     32  0.750     15   
17              0  0.402     35     87  0.303     10     33  0.652     15   
18              1  0.506     40     79  0.281      9     32  0.577     15   
19              0  0.359     28     78  0.206      7     34  0.875     14   
20              1  0.458     38     83  0.387     12     31  0.742     23   
21              1  0.460     40     87  0.387     12     31  0.821     23   
22              0  0.418     38     91  0.389     14     36  0.652     15   
23              0  0.436     41     94  0.457     16     35  0.727     16   
24              0  0.494     42     85  0.286      6     21  0.813     13   
25              0  0.453     43     95  0.405     17     42  0.765     13   
26              0  0.506     40     79  0.333     10     30  0.929     13   
27              0  0.495     45     91  0.321      9     28  0.731     19   
28              1  0.460     46    100  0.444     16     36  0.643      9   
29              0  0.430     37     86  0.324     12     37  0.667      8   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
2430            0  0.500     43     86  0.258      8     31  0.609     14   
2431            1  0.481     37     77  0.286      8     28  0.742     23   
2432            1  0.511     45     88  0.483     14     29  0.850     17   
2433            1  0.565     48     85  0.444     12     27  0.933     14   
2434            1  0.584     52     89  0.423     11     26  0.667     14   
2435            0  0.478     43     90  0.351     13     37  0.947     18   
2436            1  0.627     47     75  0.560     14     25  0.765     26   
2437            1  0.472     42     89  0.447     17     38  0.846     11   
2438            0  0.518     44     85  0.484     15     31  0.846     22   
2439            0  0.521     37     71  0.417     10     24  0.833     25   
2440            0  0.532     42     79  0.355     11     31  0.864     19   
2441            1  0.566     47     83  0.478     11     23  0.818      9   
2442            1  0.432     41     95  0.267      8     30  0.870     20   
2443            0  0.487     38     78  0.429     12     28  0.833     20   
2444            0  0.407     37     91  0.278     10     36  0.905     19   
2445            1  0.550     44     80  0.300      6     20  0.821     23   
2446            1  0.420     34     81  0.462     12     26  0.722     13   
2447            0  0.526     50     95  0.419     13     31  0.786     11   
2448            0  0.405     30     74  0.158      3     19  0.750     12   
2449            1  0.452     42     93  0.400     12     30  0.909     10   
24

In [5]:
X_val = X.values
X_val

array([[ 0.   ,  0.468, 36.   , ...,  5.   , 15.   , 18.   ],
       [ 1.   ,  0.435, 37.   , ...,  3.   , 13.   , 21.   ],
       [ 1.   ,  0.488, 39.   , ...,  3.   , 15.   , 24.   ],
       ...,
       [ 1.   ,  0.544, 49.   , ...,  6.   ,  8.   , 16.   ],
       [ 0.   ,  0.522, 47.   , ...,  0.   , 13.   , 16.   ],
       [ 0.   ,  0.349, 30.   , ...,  6.   , 15.   , 20.   ]])

In [6]:
Y.head(5)

Label
0      0
1      1
2      0
3      0
4      1

In [7]:
Y_val = Y.values
Y_val[0:5]

array([[0],
       [1],
       [0],
       [0],
       [1]])

In [8]:
Y_val = Y.values.ravel()
Y_val[0:5]

array([0, 1, 0, 0, 1])

## -Cross Validation Grid Search

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from time import time

# Set the parameters by cross-validation
tuned_max_features = ['auto', 'sqrt', 'log2']
tuned_parameters = {
                     "loss": ['deviance', 'exponential'],
                     "n_estimators": range(100, 1001, 100),
                     "learning_rate": [1, 0.5, 0.25, 0.1, 0.05, 0.01, 0.005, 0.001],
                     "max_depth": [3, 5, 8, 9, 11],
                     "subsample": [0.1, 0.5, 1],
                     "max_features": tuned_max_features
                   }

# Number of random trials
NUM_TRIALS = 1

# We will use a Support Vector Classifier with "rbf" kernel
gbm = GradientBoostingClassifier()

start = time()
(max_score, gbm_best_estimator) = CrossValidationGridSearchNested(X_val, Y_val.ravel(), NUM_TRIALS, 10, gbm, tuned_parameters, 'roc_auc')
gbm_best_parameter = gbm_best_estimator.get_params()

print("CrossValidationGridSearchNested of GradientBoostingClassifier wih NUM_TRIALS = %2.0d took %.2f seconds."%(NUM_TRIALS, (time() - start)))
print(f'\nmax_score = {max_score}\n')
print(f'\nbest_estimator = {gbm_best_estimator}\n')
print(f'\nbest_parameter = {gbm_best_parameter}\n')